### ISSUE TITLE
feature request: allow private procedures in unit

### ISSUE THREAD

**Issue by mvdhoning** [t-edson/P65Pas#7]
Currently all procedures in a unit have to be listed above the implementation to be used even within the unit itself. That way you cannot have private procedures in a unit as they cannot be used.

No need to rush this but it would be a nice to have in the future.

**Comment by t-edson** [comment]
I've identified the problem. It's because the scanner only read the INTERFACE sections of units to find identifiers. This way private elements are not read. And the order declarations are in INTERFACE is important. The solution is some hard because it needs to have infromation declaration and implementation in units. This will be for the version 0.6. I'm closing the version 0.5. Many changes have taken place here. Most of all not visibles but useful to future improves.

**Comment by t-edson** [comment]
Hi. Several changes has been done in v0.6 to support private functions in units. Now it's implemented. 
![image](https://user-images.githubusercontent.com/7736802/60153319-7e8dcc00-97a9-11e9-8991-e19a5900a047.png) There are some issues to solve but it's an advance.

**Comment by mvdhoning** [comment]
Have not noticed issues.
On a side note private variables also seem to work now, but maybe they already did.
So this feature request can be closed as it feels done.
